#!/usr/bin/env bash

set -euo pipefail

unlink=${1+1}
ln() {
	if [[ $unlink ]]; then
		rm "$2"
		return
	elif [[ -h "$2" ]]; then
		echo "already linked"
		return
	elif [[ -e "$2" ]]; then
		echo "$1 exists and is not a symlink"
		return
	fi
	command ln -s "${PWD}/$1" "$2"
}

ln git ~/.config/git
ln npmrc ~/.npmrc
ln fish ~/.config/fish

if [[ "$OSTYPE" == darwin* ]]; then
  ln sublimeText3 "${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
  ln launchAgents/set_defaults_variables.plist ~/Library/LaunchAgents/set_defaults_variables.plist
  ln gpg-agent.conf ~/.gnupg/gpg-agent.conf
fi

echo "looks good captain"
