#!/usr/bin/env bash

set -euo pipefail

unlink=${1+1}
ln() {
  if [[ $unlink ]]; then
    rm "$2"
    return
  elif [[ -L $2 ]]; then
    echo "already linked"
    return
  elif [[ -e $2 ]]; then
    echo "$1 exists and is not a symlink"
    return
  fi
  command ln -s "${PWD}/$1" "$2"
}

ln git ~/.config/git
ln nvim ~/.config/nvim
ln fish ~/.config/fish
ln mutagen.yml ~/.mutagen.yml
ln fdignore ~/.fdignore

if [[ $OSTYPE == darwin* ]]; then
  ln gpg-agent.conf ~/.gnupg/gpg-agent.conf
fi

if [[ $OSTYPE == linux-gnu ]]; then
  sudo cp -f green.timer /etc/systemd/system/green.timer
  sudo cp -f green.service /etc/systemd/system/green.service
fi

echo "looks good captain"
