#!/usr/bin/env bash

set -euo pipefail

ln() {
	if [[ -h "$2" ]]; then
		return
	elif [[ -e "$2" ]]; then
		echo "$1 exists or is already linked"
		return
	fi
	command ln -s "${PWD}/$1" "$2"
}

ln bash/bashrc ~/.bashrc 
ln git ~/.config/git
ln gpg-agent.conf ~/.gnupg/gpg-agent.conf
ln bin ~/bin
ln npmrc ~/.npmrc
ln sublimeText3 "${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
ln launchAgents/set_defaults_variables.plist ~/Library/LaunchAgents/set_defaults_variables.plist

echo "looks good captain"
