alias a="sudo apt"
alias as="sudo apt search"
alias ai="sudo apt install -y"
alias ar="sudo apt remove -y"
alias au="sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt-file update"
alias af="apt-file find"
alias fd="fdfind"
