# This prevents bash from assuming it's an interactive shell when
# it is in fact not.
# This was causing issues in the past for me as some scripts invoke bash
# with -u which causes it to error out when reading the system bashrc
# because it thinks its interactive but $PS1 is of course not set.
#  $ ssh host 'bash -xcu true'       
#  + set -x
#  /etc/bash.bashrc: line 8: PS1: unbound variable
#  + true
unset SSH_CLIENT
