source ~/src/nhooyr/dotfiles/zsh/lib.zsh
source ~/src/nhooyr/dotfiles/zsh/bookmarks.zsh

if [[ "$OSTYPE" == darwin* ]]; then
  source ~zsh/macos.zsh
elif [[ "$DISTRO" == "fedora" ]]; then
  source ~zsh/linux.zsh
fi

source_if_exists ~secrets/env.zsh || true

source ~zsh/misc.zsh
source ~zsh/completion.zsh
source ~zsh/aliases.zsh
source ~zsh/env.zsh
source ~zsh/history.zsh
source ~zsh/prompt.zsh
source ~zsh/quick.zsh
source ~zsh/remote.zsh
source ~zsh/syntax.zsh

if command_exists post_os_zshrc; then
  post_os_zshrc
fi
