name: ci
on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container: nhooyr/dotfiles-ci@sha256:230a3918a9f329d389c7795743f866a896893e3aeb420bbd601f76d4665157cd
    steps:
      - uses: actions/checkout@v1
      - run: make fmt
